<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MenusTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menus')->delete();
        
        \DB::table('menus')->insert(array (
            0 => 
            array (
                'id' => 9,
                'position' => 'cms',
                'label_id' => 8,
                'parent_id' => NULL,
                'name' => 'Developer Option',
                'name_bn' => 'ডেভেলপার অপশান',
                'system_name' => '',
                'route' => NULL,
                'slug' => NULL,
                'icon' => 'fa fa-bars',
                'status' => 1,
                'type' => 1,
                'order_by' => 2,
                'create_by' => 1,
                'deleted_at' => NULL,
                'created_at' => '2024-04-25 01:24:43',
                'updated_at' => '2024-12-02 17:14:59',
            ),
            1 => 
            array (
                'id' => 10,
                'position' => 'cms',
                'label_id' => 8,
                'parent_id' => 9,
                'name' => 'Menu Label',
                'name_bn' => 'মেনু স্তর',
                'system_name' => 'Menu Label',
                'route' => 'menu_label',
                'slug' => 'create',
                'icon' => '',
                'status' => 1,
                'type' => 2,
                'order_by' => 1,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-05-14 23:18:49',
                'updated_at' => '2024-05-15 15:31:48',
            ),
            2 => 
            array (
                'id' => 11,
                'position' => 'cms',
                'label_id' => 8,
                'parent_id' => 9,
                'name' => 'Menu',
                'name_bn' => 'মেনু',
                'system_name' => 'Menu',
                'route' => 'menu',
                'slug' => 'create',
                'icon' => '',
                'status' => 1,
                'type' => 2,
                'order_by' => 2,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-05-14 23:19:19',
                'updated_at' => '2024-05-15 15:32:30',
            ),
            3 => 
            array (
                'id' => 13,
                'position' => 'cms',
                'label_id' => 8,
                'parent_id' => NULL,
                'name' => 'Security',
                'name_bn' => 'সিকিউরিটি',
                'system_name' => NULL,
                'route' => NULL,
                'slug' => NULL,
                'icon' => 'fa fa-lock',
                'status' => 1,
                'type' => 1,
                'order_by' => 2,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-05-14 23:53:32',
                'updated_at' => '2024-05-14 23:57:33',
            ),
            4 => 
            array (
                'id' => 14,
                'position' => 'cms',
                'label_id' => 8,
                'parent_id' => 13,
                'name' => 'Role',
                'name_bn' => 'রোল',
                'system_name' => 'Role',
                'route' => 'role',
                'slug' => 'index',
                'icon' => '',
                'status' => 1,
                'type' => 2,
                'order_by' => 1,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-05-14 23:57:57',
                'updated_at' => '2024-05-15 15:32:56',
            ),
            5 => 
            array (
                'id' => 15,
                'position' => 'cms',
                'label_id' => 8,
                'parent_id' => 13,
                'name' => 'Users',
                'name_bn' => 'ইউজার',
                'system_name' => 'Users',
                'route' => 'user',
                'slug' => 'create',
                'icon' => '',
                'status' => 1,
                'type' => 2,
                'order_by' => 2,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-05-14 23:58:53',
                'updated_at' => '2024-05-15 15:33:40',
            ),
            6 => 
            array (
                'id' => 17,
                'position' => 'cms',
                'label_id' => 7,
                'parent_id' => NULL,
                'name' => 'Dashboard',
                'name_bn' => 'ড্যাশবোর্ড',
                'system_name' => 'Dashboard',
                'route' => 'admin',
                'slug' => 'view',
                'icon' => 'fa fa-home',
                'status' => 1,
                'type' => 3,
                'order_by' => 1,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-06-10 00:08:54',
                'updated_at' => '2024-06-10 00:08:54',
            ),
            7 => 
            array (
                'id' => 18,
                'position' => 'cms',
                'label_id' => 11,
                'parent_id' => NULL,
                'name' => 'Store Information',
                'name_bn' => 'স্টোর তথ্য',
                'system_name' => '',
                'route' => NULL,
                'slug' => NULL,
                'icon' => 'fa fa-shop',
                'status' => 1,
                'type' => 1,
                'order_by' => 3,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-06-10 00:15:58',
                'updated_at' => '2024-06-10 00:19:37',
            ),
            8 => 
            array (
                'id' => 19,
                'position' => 'cms',
                'label_id' => 7,
                'parent_id' => 18,
                'name' => 'Create Store',
                'name_bn' => 'স্টোর তৈরি করুন',
                'system_name' => 'Create Store',
                'route' => 'store',
                'slug' => 'create',
                'icon' => NULL,
                'status' => 1,
                'type' => 2,
                'order_by' => 1,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-06-10 00:16:48',
                'updated_at' => '2024-06-10 00:16:48',
            ),
            9 => 
            array (
                'id' => 20,
                'position' => 'cms',
                'label_id' => 11,
                'parent_id' => 18,
                'name' => 'Manage Store',
                'name_bn' => 'ম্যানেজ স্টোর',
                'system_name' => 'Manage Store',
                'route' => 'store',
                'slug' => 'index',
                'icon' => '',
                'status' => 1,
                'type' => 2,
                'order_by' => 2,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-06-10 00:17:29',
                'updated_at' => '2024-06-24 16:49:21',
            ),
            10 => 
            array (
                'id' => 22,
                'position' => 'pos',
                'label_id' => 12,
                'parent_id' => NULL,
                'name' => 'Dashboard',
                'name_bn' => 'ড্যাশবোর্ড',
                'system_name' => 'Store Dashboard',
                'route' => 'store_dashboard',
                'slug' => 'index',
                'icon' => 'fa fa-home',
                'status' => 1,
                'type' => 3,
                'order_by' => 1,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-07-03 17:46:45',
                'updated_at' => '2024-07-03 17:46:45',
            ),
            11 => 
            array (
                'id' => 23,
                'position' => 'pos',
                'label_id' => 13,
                'parent_id' => NULL,
                'name' => 'Product Settings',
                'name_bn' => 'পণ্য সেটিংস',
                'system_name' => NULL,
                'route' => NULL,
                'slug' => NULL,
                'icon' => 'fa fa-gears',
                'status' => 1,
                'type' => 1,
                'order_by' => NULL,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-07-03 23:30:21',
                'updated_at' => '2024-07-03 23:30:21',
            ),
            12 => 
            array (
                'id' => 24,
                'position' => 'pos',
                'label_id' => 13,
                'parent_id' => 32,
                'name' => 'Product Add',
                'name_bn' => 'পণ্য যুক্ত করুন',
                'system_name' => 'Product Add',
                'route' => 'product',
                'slug' => 'index',
                'icon' => '',
                'status' => 1,
                'type' => 2,
                'order_by' => 1,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-07-03 23:31:06',
                'updated_at' => '2024-11-06 16:11:56',
            ),
            13 => 
            array (
                'id' => 25,
                'position' => 'pos',
                'label_id' => 13,
                'parent_id' => 23,
                'name' => 'Item Information',
                'name_bn' => 'আইটেম তথ্য',
                'system_name' => 'Item Information',
                'route' => 'product_item',
                'slug' => 'index',
                'icon' => NULL,
                'status' => 1,
                'type' => 2,
                'order_by' => 1,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-07-05 19:37:04',
                'updated_at' => '2024-07-05 19:37:04',
            ),
            14 => 
            array (
                'id' => 26,
                'position' => 'pos',
                'label_id' => 13,
                'parent_id' => 23,
                'name' => 'Category',
                'name_bn' => 'ক্যাটাগরি',
                'system_name' => 'Category',
                'route' => 'category',
                'slug' => 'index',
                'icon' => NULL,
                'status' => 1,
                'type' => 2,
                'order_by' => 2,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-10-09 22:59:23',
                'updated_at' => '2024-10-09 22:59:23',
            ),
            15 => 
            array (
                'id' => 27,
                'position' => 'pos',
                'label_id' => 13,
                'parent_id' => 23,
                'name' => 'Brand',
                'name_bn' => 'ব্র্যান্ড',
                'system_name' => 'Brand',
                'route' => 'brand',
                'slug' => 'index',
                'icon' => NULL,
                'status' => 1,
                'type' => 2,
                'order_by' => 3,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-10-21 15:47:23',
                'updated_at' => '2024-10-21 15:47:23',
            ),
            16 => 
            array (
                'id' => 28,
                'position' => 'pos',
                'label_id' => 13,
                'parent_id' => 23,
                'name' => 'Color',
                'name_bn' => 'কালার',
                'system_name' => 'Color',
                'route' => 'color',
                'slug' => 'index',
                'icon' => NULL,
                'status' => 1,
                'type' => 2,
                'order_by' => 4,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-10-22 12:44:56',
                'updated_at' => '2024-10-22 12:44:56',
            ),
            17 => 
            array (
                'id' => 29,
                'position' => 'pos',
                'label_id' => 13,
                'parent_id' => 23,
                'name' => 'Size',
                'name_bn' => 'সাইজ',
                'system_name' => 'Size',
                'route' => 'size',
                'slug' => 'index',
                'icon' => NULL,
                'status' => 1,
                'type' => 2,
                'order_by' => 5,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-10-26 22:57:56',
                'updated_at' => '2024-10-26 22:57:56',
            ),
            18 => 
            array (
                'id' => 30,
                'position' => 'pos',
                'label_id' => 13,
                'parent_id' => 23,
                'name' => 'Unit',
                'name_bn' => 'ইউনিট',
                'system_name' => 'Unit',
                'route' => 'unit',
                'slug' => 'index',
                'icon' => NULL,
                'status' => 1,
                'type' => 2,
                'order_by' => 6,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-10-29 00:16:28',
                'updated_at' => '2024-10-29 00:16:28',
            ),
            19 => 
            array (
                'id' => 31,
                'position' => 'pos',
                'label_id' => 13,
                'parent_id' => 23,
                'name' => 'Sub Unit',
                'name_bn' => 'সাব ইউনিট',
                'system_name' => 'Sub Unit',
                'route' => 'sub_unit',
                'slug' => 'index',
                'icon' => NULL,
                'status' => 1,
                'type' => 2,
                'order_by' => 8,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-11-06 00:42:00',
                'updated_at' => '2024-11-06 00:42:00',
            ),
            20 => 
            array (
                'id' => 32,
                'position' => 'pos',
                'label_id' => 13,
                'parent_id' => NULL,
                'name' => 'Product information',
                'name_bn' => 'পণ্য তথ্য',
                'system_name' => NULL,
                'route' => NULL,
                'slug' => NULL,
                'icon' => 'fa fa-product-hunt',
                'status' => 1,
                'type' => 1,
                'order_by' => 3,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-11-06 16:11:30',
                'updated_at' => '2024-11-06 16:11:30',
            ),
            21 => 
            array (
                'id' => 33,
                'position' => 'pos',
                'label_id' => 14,
                'parent_id' => NULL,
                'name' => 'Supplier Information',
                'name_bn' => 'সাপ্লাইয়ার্স তথ্য',
                'system_name' => NULL,
                'route' => NULL,
                'slug' => NULL,
                'icon' => 'fa fa-users',
                'status' => 1,
                'type' => 1,
                'order_by' => 3,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-11-21 23:57:21',
                'updated_at' => '2024-11-21 23:57:21',
            ),
            22 => 
            array (
                'id' => 34,
                'position' => 'pos',
                'label_id' => 14,
                'parent_id' => 33,
                'name' => 'Supplier Area',
                'name_bn' => 'সাপ্লাইয়ার এরিয়া',
                'system_name' => 'Supplier Area',
                'route' => 'supplier_area',
                'slug' => 'index',
                'icon' => NULL,
                'status' => 1,
                'type' => 2,
                'order_by' => 1,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-11-21 23:59:29',
                'updated_at' => '2024-11-21 23:59:29',
            ),
            23 => 
            array (
                'id' => 35,
                'position' => 'pos',
                'label_id' => 14,
                'parent_id' => 33,
                'name' => 'Supplier Info',
                'name_bn' => 'সাপ্লাইয়ার তথ্য',
                'system_name' => 'Supplier Info',
                'route' => 'supplier',
                'slug' => 'index',
                'icon' => NULL,
                'status' => 1,
                'type' => 2,
                'order_by' => 2,
                'create_by' => 3,
                'deleted_at' => NULL,
                'created_at' => '2024-11-23 17:06:15',
                'updated_at' => '2024-11-23 17:06:15',
            ),
        ));
        
        
    }
}